name: Main CI

concurrency:
  group: ci-${{ github.ref }}-main
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main
      - 'release/*'
  merge_group:
    types: [checks_requested]

env:
  NX_PARALLEL: ${{ vars.NX_PARALLEL }}
  NX_TASK_TARGET_CONFIGURATION: ci
  YARN_ENABLE_HARDENED_MODE: 0
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  # Check the integrity of yarn lock
  yarn_lock_check:
    runs-on: ubuntu-latest
    env:
      NX_SKIP_NX_CACHE: true
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
#      - uses: ./tools/github-actions/setup
#        env:
#          YARN_ENABLE_HARDENED_MODE: 1
      - name: Yarn errors reporter
        uses: ./tools/github-actions/yarn-errors-reporter
